<a href="https://colab.research.google.com/github/swarna32/Depression/blob/main/Depression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
news_data = pd.read_csv('/content/drive/MyDrive/content/depression_dataset_reddit_cleaned.csv')

In [ ]:
news_data

clean_text  is_depression
0     we understand that most people who reply immed...              1
1     welcome to r depression s check in post a plac...              1
2     anyone else instead of sleeping more when depr...              1
3     i ve kind of stuffed around a lot in my life d...              1
4     sleep is my greatest and most comforting escap...              1
...                                                 ...            ...
7726                                       is that snow              0
7727                 moulin rouge mad me cry once again              0
7728  trying to shout but can t find people on the list              0
7729  ughh can t find my red sox hat got ta wear thi...              0
7730  slept wonderfully finally tried swatching for ...              0

[7731 rows x 2 columns]

In [ ]:
y = news_data['is_depression']

In [ ]:
y

0       1
1       1
2       1
3       1
4       1
       ..
7726    0
7727    0
7728    0
7729    0
7730    0
Name: is_depression, Length: 7731, dtype: int64

In [ ]:
news_data.is_depression.unique()

array([1, 0])

In [ ]:
# y = y.to_numpy().astype('str')

In [ ]:
y

0       1
1       1
2       1
3       1
4       1
       ..
7726    0
7727    0
7728    0
7729    0
7730    0
Name: is_depression, Length: 7731, dtype: int64

In [ ]:
news_body = news_data.iloc[:,1]

In [ ]:
news_body

0       1
1       1
2       1
3       1
4       1
       ..
7726    0
7727    0
7728    0
7729    0
7730    0
Name: is_depression, Length: 7731, dtype: int64

In [ ]:
news_body = news_data['clean_text']

In [ ]:
t=news_body.to_numpy()

In [ ]:
t

array(['we understand that most people who reply immediately to an op with an invitation to talk privately mean only to help but this type of response usually lead to either disappointment or disaster it usually work out quite differently here than when you say pm me anytime in a casual social context we have huge admiration and appreciation for the goodwill and good citizenship of so many of you who support others here and flag inappropriate content even more so because we know that so many of you are struggling yourselves we re hard at work behind the scene on more information and resource to make it easier to give and get quality help here this is just a small start our new wiki page explains in detail why it s much better to respond in public comment at least until you ve gotten to know someone it will be maintained at r depression wiki private contact and the full text of the current version is below summary anyone who while acting a a helper invite or accepts private contact i e 

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
from nltk.stem import WordNetLemmatizer
import re
documents = []
stemmer = WordNetLemmatizer()
for sen in range(0, len(t)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(t[sen]))
    # remove all single characters from middle
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document)
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    # Converting to Lowercase
    document = document.lower()
    document = re.sub("^\d+\s|\s\d+\s|\s\d+$", ' ', document)
    # Lemmatization
    document = document.split()
    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    documents.append(document)

In [ ]:
documents

['we understand that most people who reply immediately to an op with an invitation to talk privately mean only to help but this type of response usually lead to either disappointment or disaster it usually work out quite differently here than when you say pm me anytime in casual social context we have huge admiration and appreciation for the goodwill and good citizenship of so many of you who support others here and flag inappropriate content even more so because we know that so many of you are struggling yourselves we re hard at work behind the scene on more information and resource to make it easier to give and get quality help here this is just small start our new wiki page explains in detail why it much better to respond in public comment at least until you ve gotten to know someone it will be maintained at depression wiki private contact and the full text of the current version is below summary anyone who while acting a helper invite or accepts private contact e pm chat or any kin

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
vectorizer = TfidfVectorizer( encoding='utf-8',stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()
terms = vectorizer.get_feature_names()
print(len(terms))

18659


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
X.shape

(7731, 18659)

In [ ]:
terms

['00',
 '000',
 '000mg',
 '000s',
 '00am',
 '00b',
 '00bpm',
 '00db',
 '00g',
 '00k',
 '00lb',
 '00mb',
 '00mg',
 '00ml',
 '00mph',
 '00ms',
 '00th',
 '00usd',
 '0am',
 '0ci',
 '0f',
 '0g',
 '0gxfpnbrsx',
 '0h',
 '0hrs',
 '0i',
 '0ish',
 '0k',
 '0kg',
 '0km',
 '0kms',
 '0lbs',
 '0m',
 '0mbps',
 '0mg',
 '0mgs',
 '0min',
 '0mins',
 '0ml',
 '0p',
 '0pm',
 '0pt',
 '0secondstomars',
 '0th',
 '0uhhroudrr',
 '0verdose',
 '0virgin',
 '0x',
 '0yo',
 '0yongk',
 '0yr',
 '0yrs',
 '0zr',
 '90',
 '90ish',
 '90k',
 '99',
 '9am',
 '9f',
 '9hr',
 '9inches',
 '9m',
 '9md',
 '9p',
 '9pm',
 '9sjtg',
 '9sscse9',
 '9th',
 '9u',
 '9yr',
 '9zd',
 'a9hjljkr',
 'aa',
 'aaaaaaaa',
 'aaaaaaaaaah',
 'aaaaaaaaah',
 'aaaaah',
 'aaaaand',
 'aaaah',
 'aaand',
 'aaguthu',
 'aahmddr',
 'aalexaanne',
 'aaliyah',
 'aalsmeer',
 'aaroncikaya',
 'aaronrva',
 'aarp',
 'aarya',
 'aastha',
 'aate',
 'aaw',
 'aawwwww',
 'ab',
 'abacab',
 'aback',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abbey',
 'abdomen',
 'ab

In [ ]:
print(terms[10344])

messiness


In [ ]:
# Y=[]
# for i in range(len(y)):
#     if y[i] =='positive':
#       Y.append(0)
#     elif y[i] == 'negative':
#       Y.append(1)
#     elif y[i] == 'neutral':
#       Y.append(2)



In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)



In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1000, random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[737  42]
 [ 58 710]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       779
           1       0.94      0.92      0.93       768

    accuracy                           0.94      1547
   macro avg       0.94      0.94      0.94      1547
weighted avg       0.94      0.94      0.94      1547

0.9353587588881707


In [ ]:
pred_prob = classifier.predict_proba(X_test)

In [ ]:
len(pred_prob)

1547

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))


[[576 203]
 [ 57 711]]
              precision    recall  f1-score   support

           0       0.91      0.74      0.82       779
           1       0.78      0.93      0.85       768

    accuracy                           0.83      1547
   macro avg       0.84      0.83      0.83      1547
weighted avg       0.84      0.83      0.83      1547

0.8319327731092437


In [ ]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(random_state=0)
DT.fit(X_train, y_train)
y_pred = DT.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))


[[654 125]
 [ 63 705]]
              precision    recall  f1-score   support

           0       0.91      0.84      0.87       779
           1       0.85      0.92      0.88       768

    accuracy                           0.88      1547
   macro avg       0.88      0.88      0.88      1547
weighted avg       0.88      0.88      0.88      1547

0.8784744667097608


In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state=0).fit(X, y)
LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))


[[758  21]
 [ 67 701]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.95       779
           1       0.97      0.91      0.94       768

    accuracy                           0.94      1547
   macro avg       0.94      0.94      0.94      1547
weighted avg       0.94      0.94      0.94      1547

0.9431157078215902


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=3)
KNN.fit(X_train, y_train)
y_pred = KNN.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[567 212]
 [ 77 691]]
              precision    recall  f1-score   support

           0       0.88      0.73      0.80       779
           1       0.77      0.90      0.83       768

    accuracy                           0.81      1547
   macro avg       0.82      0.81      0.81      1547
weighted avg       0.82      0.81      0.81      1547

0.8131868131868132
